name:                the-mutant-sdl
version:             0.1.0.0
github:              "schell/the-mutant-sdl"
license:             BSD3
author:              "Schell Scivally"
maintainer:          "efsubenovex@gmail.com"
copyright:           "2019 Schell Scivally"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/the-mutant-sdl#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- lens
- linear
- freetype2
- JuicyPixels
- mtl
- sdl2
- text
- the-mutant
- typograffiti-sdl
- vector

library:
  source-dirs: src

tests:
  the-mutant-sdl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - the-mutant-sdl
