name:                the-mutant-sdl
version:             0.1.0.0
github:              "schell/the-mutant-sdl"
license:             BSD3
author:              "Schell Scivally"
maintainer:          "efsubenovex@gmail.com"
copyright:           "2019 Schell Scivally"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/the-mutant-sdl#readme>

dependencies:
- base             >= 4.7 && < 5
- directory        >= 1.3.3.0
- lens             >= 4.17.1
- linear           >= 1.20.8
- freetype2        >= 0.1.2
- JuicyPixels      >= 3.3.3
- mtl              >= 2.2.2
- sdl2             >= 2.4.1
- text             >= 1.2.3.1
- the-mutant       >= 0.1
- typograffiti-sdl >= 0.1
- vector           >= 0.12

library:
  source-dirs: src

#tests:
#  the-mutant-sdl-test:
#    main:                Spec.hs
#    source-dirs:         test
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - the-mutant-sdl
