name:                free-gui
version:             0.1.0.0
github:              "githubuser/free-gui"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/free-gui#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- polysemy
- polysemy-plugin
- jsaddle
- jsaddle-warp

library:
  source-dirs: src

executables:
  free-gui-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Polysemy.Plugin
    - -O2
    - -flate-specialise
    - -fspecialise-aggressively
    dependencies:
    - free-gui

tests:
  free-gui-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - free-gui
