name:                the-mutant
version:             0.1.0.0
github:              "schell/the-mutant"
license:             BSD3
author:              "Schell Scivally"
maintainer:          "schell@formation.ai"
copyright:           "2019 Schell Scivally"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/schell/the-mutant#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- data-fix
- jsaddle
- jsaddle-warp
- lens
- polysemy
- polysemy-plugin
- text
- vector

library:
  source-dirs: src
  ghc-options:
  - -fplugin=Polysemy.Plugin
  - -fconstraint-solver-iterations=0
  - -Wall

executables:
  free-gui-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -flate-specialise
    - -fspecialise-aggressively
    dependencies:
    - the-mutant

tests:
  free-gui-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - the-mutant
