name:                the-mutant
version:             0.1.0.0
github:              "schell/the-mutant"
license:             BSD3
author:              "Schell Scivally"
maintainer:          "schell@formation.ai"
copyright:           "2019 Schell Scivally"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/schell/the-mutant#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- data-fix
- directory
- freetype2
- jsaddle
- jsaddle-warp
- JuicyPixels
- lens
- linear
- mtl
- sdl2
- text
- transformers
- typograffiti-sdl
- vector
- wai-app-static
- warp
- websockets

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  render2d-exe:
    main:                Main.hs
    source-dirs:         app/Renders2d
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - async
    - the-mutant


tests:
  free-gui-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - the-mutant
