name:                the-mutant
version:             0.1.0.0
github:              "schell/the-mutant"
license:             BSD3
author:              "Schell Scivally"
maintainer:          "schell@formation.ai"
copyright:           "2019 Schell Scivally"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/schell/the-mutant#readme>

dependencies:
- base         >= 4.7 && < 5
- containers   >= 0.6.0.1
- linear       >= 1.20.8
- mtl          >= 2.2.2
- text         >= 1.2.3.1
- transformers >= 0.5.6.2
- vector       >= 0.12.0.2

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror

tests:
  free-gui-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - the-mutant
