name:                the-mutant-app-js
version:             0.1.0.0
github:              "schell/the-mutant-app-js"
license:             BSD3
author:              "Schell Scivally"
maintainer:          "efsubenovex@gmail.com"
copyright:           "2019 Schell Scivally"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/schell/the-mutant#readme>

executables:
  the-mutant-app-js-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base           >= 4.7 && < 5
    - linear         >= 1.20.8
    - the-mutant-app >= 0.1
    - the-mutant-js  >= 0.1
